Repository najitwo/10-Sprint-Taskify, pull requests merged in 2024-12, with the labels that each got.

#118 [feat] add login and signup modal
  src/app/(user-access)/components/modal/Modal.module.css
  src/app/(user-access)/components/modal/Modal.tsx
  src/app/(user-access)/components/modal/ModalContainer.tsx
  src/app/(user-access)/layout.module.css
  src/app/(user-access)/lib/loginService.ts
  src/app/(user-access)/lib/signupService.ts
  src/app/(user-access)/login/loginPage.module.css
  src/app/(user-access)/login/page.tsx
  src/app/(user-access)/modalStore/modalStore.ts
  src/app/(user-access)/signup/page.tsx
  src/app/(user-access)/signup/signPage.module.css
  src/constants/message.ts
  src/constants/regex.ts
Labels: ✨Feature

#126 [fix] manage multiple cards in card store
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/UpdateCardModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/DashboardCard.tsx
  src/components/sidebar/Dashboards.tsx
  src/store/cardStore.ts
Labels: 🐞BugFix

#129 [style] improve dashboard uiux
  public/images/logo.svg
  public/images/logo_symbol.svg
  public/images/logo_typo.svg
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/app/page.tsx
  src/components/CustomLogo.tsx
  src/components/MainContainer.module.css
  src/components/landing/Header/Header.module.css
  src/components/landing/Header/Header.tsx
  src/components/landing/Section/HeroSection.tsx
  src/components/landing/Section/MainCard.module.css
  src/components/landing/Section/MainCard.tsx
  src/components/landing/Section/MiniCard.module.css
  src/components/landing/Section/MiniCard.tsx
  src/components/landing/Section/PrimarySection.tsx
  src/components/landing/Section/SecondarySection.tsx
  src/components/landing/layout.tsx
Labels: 🎨HTML&CSS

#130 [fix] redirection for non token
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateColumnModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useMember.ts
  src/components/header/DashboardMembers.tsx
  src/components/header/UserSection.tsx
  src/middleware.ts
Labels: 🐞BugFix

#132 [fix] resolve delete column error
  src/app/(with-header-sidebar)/dashboard/[id]/components/SettingsColumnModal.tsx
Labels: 🐞BugFix

#133 [docs] add README.md
  README.md
Labels: 📃Docs

#134 [docs] update README.md
  README.md
Labels: 📃Docs
