Repository najitwo/10-Sprint-Taskify, pull requests merged in 2024-11, with the labels that each got.

#2 [feat] add header and sidebar layout
  .eslintrc.json
  package.json
  src/app/(with-header-sidebar)/layout.module.css
  src/app/(with-header-sidebar)/layout.tsx
  src/app/(with-header-sidebar)/mydashboard/page.tsx
  src/components/Header.module.css
  src/components/Header.tsx
  src/components/SideBar.module.css
  src/components/SideBar.tsx
Labels: ✨Feature, 🌏Deploy

#6 [feat] add forms to mypage
  src/app/mypage/components/Button.module.css
  src/app/mypage/components/Button.tsx
  src/app/mypage/components/FileInput.module.css
  src/app/mypage/components/FileInput.tsx
  src/app/mypage/components/Input.module.css
  src/app/mypage/components/Input.tsx
  src/app/mypage/components/Label.module.css
  src/app/mypage/components/Label.tsx
  src/app/mypage/components/PasswordForm.module.css
  src/app/mypage/components/PasswordForm.tsx
  src/app/mypage/components/ProfileForm.module.css
  src/app/mypage/components/ProfileForm.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
Labels: ✨Feature

#10 ✨ feat: add common button component
  src/components/Button.module.css
  src/components/Button.tsx
Labels: ✨Feature

#11 [feat] add header and sidebar css and types
  src/app/(with-header-sidebar)/layout.module.css
  src/app/(with-header-sidebar)/layout.tsx
  src/app/(with-header-sidebar)/mydashboard/hooks/useApi.ts
  src/app/(with-header-sidebar)/mydashboard/hooks/useWindowSize.ts
  src/app/(with-header-sidebar)/mydashboard/types/dashboards.ts
  src/app/(with-header-sidebar)/mydashboard/types/user.ts
  src/app/(with-header-sidebar)/mydashboard/utils/axiosInstance.ts
  src/app/reset.css
  src/components/Button.tsx
  src/components/Header.module.css
  src/components/Header.tsx
  src/components/MainContainer.module.css
  src/components/MainContainer.tsx
  src/components/SideBar.module.css
  src/components/SideBar.tsx
  src/constants/urls.ts
Labels: 🎨HTML&CSS, 📬API

#14 [feat] integrate user api for mypage
  .eslintrc.json
  src/app/mypage/components/Button.module.css
  src/app/mypage/components/Button.tsx
  src/app/mypage/components/FileInput.tsx
  src/app/mypage/components/Form.module.css
  src/app/mypage/components/Input.module.css
  src/app/mypage/components/PasswordForm.tsx
  src/app/mypage/components/ProfileForm.module.css
  src/app/mypage/components/ProfileForm.tsx
  src/app/mypage/constants/message.ts
  src/app/mypage/hooks/useAuth.ts
  src/app/mypage/lib/authHelper.ts
  src/app/mypage/lib/axios.ts
  src/app/mypage/page.tsx
  src/app/mypage/store/authStore.ts
  src/app/mypage/types/user.ts
Labels: ✨Feature, 📬API

#12 [feat] add layout for landing page
  next.config.ts
  package-lock.json
  package.json
  public/icons/email.svg
  public/icons/facebook.svg
  public/icons/instagram.svg
  public/images/home.png
  public/images/landing_lg_1.png
  public/images/landing_lg_2.png
  public/images/landing_sm_1.png
  public/images/landing_sm_2.png
  public/images/landing_sm_3.png
  public/images/logo.svg
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/app/reset.css
  src/components/root/CustomLogo.tsx
  src/components/root/ImageWrapper.module.css
  src/components/root/ImageWrapper.tsx
  src/components/root/MainCard.module.css
  src/components/root/MainCard.tsx
  src/components/root/MiniCard.module.css
  src/components/root/MiniCard.tsx
  src/svg.d.ts
  tsconfig.json
Labels: ✨Feature, 🎨HTML&CSS

#18 [feat] add sidebar dashboards
  src/app/(with-header-sidebar)/layout.module.css
  src/app/(with-header-sidebar)/mydashboard/_hooks/useApi.ts
  src/app/(with-header-sidebar)/mydashboard/_utils/axiosInstance.ts
  src/app/reset.css
  src/components/header/Header.module.css
  src/components/header/Header.tsx
  src/components/header/UserInfo.module.css
  src/components/header/UserInfo.tsx
  src/components/sidebar/Dashboards.module.css
  src/components/sidebar/Dashboards.tsx
  src/components/sidebar/SideBar.module.css
  src/components/sidebar/SideBar.tsx
  src/types/user.ts
Labels: 🎨HTML&CSS, 📬API

#9 [feat] add login functionality
  src/api/auth/login.ts
  src/api/auth/signup.ts
  src/store/authStore.ts
Labels: ✨Feature

#26 [feat] add mypage layout and responsive CSS
  src/app/(with-header-sidebar)/mypage/_components/AlertModal.module.css
  src/app/(with-header-sidebar)/mypage/_components/AlertModal.tsx
  src/app/(with-header-sidebar)/mypage/_components/FileInput.module.css
  src/app/(with-header-sidebar)/mypage/_components/FileInput.tsx
  src/app/(with-header-sidebar)/mypage/_components/Form.module.css
  src/app/(with-header-sidebar)/mypage/_components/Input.module.css
  src/app/(with-header-sidebar)/mypage/_components/Input.tsx
  src/app/(with-header-sidebar)/mypage/_components/Label.module.css
  src/app/(with-header-sidebar)/mypage/_components/Label.tsx
  src/app/(with-header-sidebar)/mypage/_components/Modal.module.css
  src/app/(with-header-sidebar)/mypage/_components/Modal.tsx
  src/app/(with-header-sidebar)/mypage/_components/PasswordForm.tsx
  src/app/(with-header-sidebar)/mypage/_components/ProfileForm.tsx
  src/app/(with-header-sidebar)/mypage/_constants/message.ts
  src/app/(with-header-sidebar)/mypage/_hooks/useAuth.ts
  src/app/(with-header-sidebar)/mypage/_lib/axios.ts
  src/app/(with-header-sidebar)/mypage/_lib/userService.ts
  src/app/(with-header-sidebar)/mypage/_store/authStore.ts
  src/app/(with-header-sidebar)/mypage/_store/modalStore.ts
  src/app/(with-header-sidebar)/mypage/layout.module.css
  src/app/(with-header-sidebar)/mypage/layout.tsx
  src/app/(with-header-sidebar)/mypage/page.module.css
  src/app/(with-header-sidebar)/mypage/page.tsx
  src/app/layout.tsx
  src/app/mypage/components/Form.module.css
  src/app/mypage/components/ProfileForm.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/types/user.ts
  src/app/page.module.css
Labels: ✨Feature, 🎨HTML&CSS

#27 [feat] add login check and responsive design
  src/app/page.tsx
  src/app/reset.css
  src/components/CustomLogo.tsx
  src/components/ImageWrapper.module.css
  src/components/ImageWrapper.tsx
  src/components/landing/Footer/Footer.module.css
  src/components/landing/Footer/Footer.tsx
  src/components/landing/Header/Header.module.css
  src/components/landing/Header/Header.tsx
  src/components/landing/Section/HeroSection.module.css
  src/components/landing/Section/HeroSection.tsx
  src/components/landing/Section/MainCard.module.css
  src/components/landing/Section/MainCard.tsx
  src/components/landing/Section/MiniCard.module.css
  src/components/landing/Section/MiniCard.tsx
  src/components/landing/Section/PrimarySection.module.css
  src/components/landing/Section/PrimarySection.tsx
  src/components/landing/Section/SecondarySection.module.css
  src/components/landing/Section/SecondarySection.tsx
  src/components/landing/layout.module.css
  src/components/landing/layout.tsx
Labels: 🔨Refactor, 🎨HTML&CSS

#34 [feat] add new dashboard modal
  src/app/(with-header-sidebar)/layout.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/Input.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/Input.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardCard.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardCard.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardForm.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/Dashboards.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/Dashboards.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/Invitations.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/modal/FocusTrap.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.tsx
  src/app/(with-header-sidebar)/mydashboard/_constants/message.ts
  src/app/(with-header-sidebar)/mydashboard/_hooks/useModal.ts
  src/app/(with-header-sidebar)/mydashboard/page.module.css
  src/components/MainContainer.module.css
  src/components/MainContainer.tsx
  src/components/header/Header.module.css
  src/components/sidebar/SideBar.module.css
Labels: ✨Feature

#40 [feat] add dashboard
  next.config.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/boardService.ts
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardForm.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/AddDashboardForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardCard.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardCard.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/Dashboards.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.module.css
  src/app/(with-header-sidebar)/mydashboard/_lib/axiosInstance.ts
  src/app/(with-header-sidebar)/mydashboard/_lib/dashboardsApi.ts
  src/components/Button.module.css
  src/components/DashboardInput.module.css
  src/components/DashboardInput.tsx
  src/components/header/Header.tsx
  src/components/header/UserInfo.tsx
  src/components/header/skeleton/UserInfoSkeleton.module.css
  src/components/header/skeleton/UserInfoSkeleton.tsx
  src/components/sidebar/SideBar.module.css
  src/components/sidebar/SideBar.tsx
  src/types/dashboards.ts
Labels: 🎨HTML&CSS, 📬API

#43 [feat] add invitation list
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Invitations.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Invitations.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Pagination.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Pagination.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useApi.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useInvitation.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/invitationService.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.tsx
  src/types/invitation.ts
Labels: ✨Feature

#46 [fix] remove property on DashboardInput
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
Labels: 🐞BugFix

#49 [feat] mydashboard invitations
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/Invitations.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.tsx
  src/app/(with-header-sidebar)/mydashboard/_hooks/useMyInvitations.ts
  src/app/(with-header-sidebar)/mydashboard/_lib/myInvitationService.ts
  src/app/(with-header-sidebar)/mydashboard/page.tsx
  src/lib/axiosInstance.ts
  src/types/invitation.ts
Labels: 📬API

#51 [chore] include build test in Github Action workflow
  .github/workflows/lint.yml
Labels: ⚙Setting

#50 [feat] add invitation modal and cancel invitation
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EmptyInvitations.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EmptyInvitations.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/InvitationModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/InvitationModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Invitations.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Invitations.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListHeader.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListHeader.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Pagination.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Pagination.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useInvitation.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/invitationService.ts
  src/app/(with-header-sidebar)/mypage/_components/Modal.tsx
  src/constants/message.ts
Labels: ✨Feature

#42 [feat] add login page
  src/app/(user-access)/login/loginPage.module.css
  src/app/(user-access)/login/page.tsx
  src/app/(user-access)/signup/page.tsx
  src/constants/message.ts
Labels: ✨Feature, 🎨HTML&CSS

#53 [feat] my invitations filtering and css
  src/app/(user-access)/signup/page.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationCard.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationCard.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationHeader.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationHeader.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/SearchBar.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/SearchBar.tsx
  src/app/(with-header-sidebar)/mydashboard/_hooks/useMyInvitations.ts
  src/components/sidebar/SideBar.tsx
Labels: 🎨HTML&CSS

#47 [feat] add default layout
  next.config.ts
  package-lock.json
  package.json
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
Labels: ✨Feature, 📬API

#57 [feat] add accept my invitation api call
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationCard.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.tsx
  src/app/(with-header-sidebar)/mydashboard/_hooks/useMyInvitations.ts
  src/app/(with-header-sidebar)/mydashboard/_lib/myInvitationService.ts
  src/types/invitation.ts
Labels: 📬API

#55 [feat] add member list
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Invitations.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListHeader.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Members.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/Members.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useApi.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useInvitation.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useMember.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/invitationService.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/memberService.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.tsx
  src/components/Avatar.module.css
  src/components/Avatar.tsx
  src/types/member.ts
Labels: ✨Feature, 🎨HTML&CSS

#65 [feat] add dashboard deletion
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EditForm.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/components/Avatar.module.css
  src/components/Avatar.tsx
  src/lib/boardService.ts
Labels: ✨Feature, 🔨Refactor

#62 [refactor] split components into separate files
  package-lock.json
  package.json
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useDashBoardView.ts
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/components/sidebar/Dashboards.tsx
  src/types/dashboardView.ts
Labels: ✨Feature, 🔨Refactor

#68 [feat] add dashboard store and header title value
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/components/MainContainer.tsx
  src/components/header/DashboardMembers.module.css
  src/components/header/DashboardMembers.tsx
  src/components/header/Header.module.css
  src/components/header/Header.tsx
  src/components/header/Title.module.css
  src/components/header/Title.tsx
  src/components/header/UserInfo.module.css
  src/components/header/UserInfo.tsx
  src/components/sidebar/Dashboards.module.css
  src/components/sidebar/Dashboards.tsx
  src/store/dashboardStore.ts
Labels: ✨Feature, 🔨Refactor

#70 [feat] header members
  src/components/Avatar.tsx
  src/components/header/DashboardMembers.module.css
  src/components/header/DashboardMembers.tsx
  src/components/header/Header.module.css
  src/components/header/Header.tsx
Labels: ✨Feature

#72 [fix] add dashboard null check on title
  src/components/header/Title.tsx
Labels: 🐞BugFix

#73 main <- develop
  package-lock.json
  package.json
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EditForm.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/ListItem.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/page.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useDashBoardView.ts
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/components/Avatar.module.css
  src/components/Avatar.tsx
  src/components/MainContainer.tsx
  src/components/header/DashboardMembers.module.css
  src/components/header/DashboardMembers.tsx
  src/components/header/Header.module.css
  src/components/header/Header.tsx
  src/components/header/Title.module.css
  src/components/header/Title.tsx
  src/components/header/UserInfo.module.css
  src/components/header/UserInfo.tsx
  src/components/sidebar/Dashboards.module.css
  src/components/sidebar/Dashboards.tsx
  src/lib/boardService.ts
  src/store/dashboardStore.ts
  src/types/dashboardView.ts
Labels: 🌏Deploy

#77 [feat] card view assignment css
  public/icons/x_lg.svg
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.tsx
  src/app/(with-header-sidebar)/mydashboard/_hooks/useIntersectionObserver.ts
  src/app/(with-header-sidebar)/mydashboard/_hooks/useMyInvitations.ts
  src/components/header/Header.tsx
  src/lib/boardService.ts
  src/types/dashboardView.ts
  src/utils/dateUtils.ts
Labels: 🔨Refactor, 🎨HTML&CSS

#78 [feat] implement dropdown and calendar
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateTaskModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateTaskModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/DatePicker.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/DatePicker.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/SearchDropdown.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/SearchDropdown.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/ClientLayout.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/InvitationModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/InvitationModal.tsx
  src/app/(with-header-sidebar)/layout.tsx
  src/app/(with-header-sidebar)/mypage/_components/FocusTrap.tsx
  src/app/(with-header-sidebar)/mypage/_components/Modal.module.css
  src/app/(with-header-sidebar)/mypage/_components/Modal.tsx
  src/app/(with-header-sidebar)/mypage/layout.tsx
  src/components/Avatar.tsx
  src/store/modalStore.ts
Labels: ✨Feature, 🔨Refactor

#74 [feat] add infinte scroll
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useDashBoardView.ts
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/types/dashboardView.ts
Labels: ✨Feature, 📬API

#76 [fix] resolve style and hydration
  src/app/layout.tsx
  src/app/page.module.css
  src/app/reset.css
  src/components/ImageWrapper.tsx
  src/components/landing/Header/Header.tsx
  src/components/landing/Section/HeroSection.module.css
  src/components/landing/Section/HeroSection.tsx
  src/components/landing/layout.module.css
Labels: 🎨HTML&CSS

#82 [feat] card view and delete
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useMember.ts
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.module.css
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.tsx
  src/app/(with-header-sidebar)/mydashboard/_hooks/useApi.ts
  src/components/Avatar.tsx
  src/components/MenuDropdown.module.css
  src/components/MenuDropdown.tsx
  src/components/card/ColumnLabel.module.css
  src/components/card/ColumnLabel.tsx
  src/components/card/Tag.module.css
  src/components/card/Tag.tsx
  src/components/header/DashboardMembers.tsx
  src/components/header/Header.module.css
  src/components/header/Header.tsx
  src/components/header/UserSection.module.css
  src/components/header/UserSection.tsx
  src/components/svg/Dot.tsx
  src/components/svg/More.tsx
  src/components/svg/Pipe.tsx
  src/hooks/useMenu.ts
  src/lib/cardService.ts
  src/types/dashboardView.ts
  src/types/menu.ts
  src/utils/colorUtils.ts
Labels: ✨Feature, 🔨Refactor

#61 [feat] add auth layout
  src/app/(user-access)/layout.module.css
  src/app/(user-access)/layout.tsx
  src/app/(user-access)/login/loginPage.module.css
  src/app/(user-access)/login/page.tsx
  src/app/(user-access)/signup/signPage.module.css
Labels: 🔨Refactor, 🎨HTML&CSS

#87 [feat] add task modal features and api integration
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateTaskModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateTaskModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/DatePicker.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/DatePicker.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/SearchDropdown.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/SearchDropdown.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useMember.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_lib/memberService.ts
  src/app/(with-header-sidebar)/mypage/_components/Label.module.css
  src/app/(with-header-sidebar)/mypage/_components/Label.tsx
  src/app/(with-header-sidebar)/mypage/_components/Modal.module.css
  src/app/(with-header-sidebar)/mypage/_components/ProfileForm.tsx
  src/components/FileInput.module.css
  src/components/FileInput.tsx
  src/components/Input.module.css
  src/components/Input.tsx
  src/components/TagsInput.module.css
  src/components/TagsInput.tsx
  src/components/Textarea.module.css
  src/components/Textarea.tsx
  src/components/card/Tag.module.css
  src/components/card/Tag.tsx
  src/constants/message.ts
  src/lib/cardService.ts
  src/utils/dateUtils.ts
Labels: ✨Feature, 🎨HTML&CSS, 📬API

#90 [feat] implement comments fetch
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Comments.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Comments.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useComment.ts
  src/lib/commentService.ts
  src/types/comment.ts
Labels: ✨Feature, 📬API

#96 [feat] card preview css
  src/app/(user-access)/layout.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/components/TagsInput.tsx
  src/components/header/UserInfo.tsx
Labels: 🎨HTML&CSS

#93 [feat] comment creation
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Comments.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/CreateCommentForm.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/CreateCommentForm.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useInvitation.ts
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useComment.ts
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.tsx
  src/components/header/Header.tsx
  src/lib/commentService.ts
  src/types/comment.ts
Labels: ✨Feature, 🐞BugFix

#98 [feat] add responsive design to landing page
  src/components/landing/Footer/Footer.module.css
  src/components/landing/Header/Header.module.css
  src/components/landing/Section/HeroSection.module.css
  src/components/landing/Section/MainCard.module.css
  src/components/landing/Section/MainCard.tsx
  src/components/landing/Section/MiniCard.module.css
  src/components/landing/Section/PrimarySection.module.css
  src/components/landing/Section/PrimarySection.tsx
  src/components/landing/Section/SecondarySection.module.css
  src/components/landing/Section/SecondarySection.tsx
  src/components/landing/layout.module.css
Labels: 🎨HTML&CSS

#97 [feat] add responsive design to dashboardView
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/components/sidebar/Dashboards.tsx
  src/store/dashboardStore.ts
Labels: 🎨HTML&CSS

#101 fix: final resolved conflict
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
Labels: 🐞BugFix

#99 [feat] add login state
  package-lock.json
  package.json
  src/app/(user-access)/login/page.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Comments.module.css
  src/app/(with-header-sidebar)/mypage/_lib/axios.ts
  src/app/(with-header-sidebar)/mypage/page.tsx
  src/components/header/UserInfo.tsx
  src/components/header/UserSection.tsx
  src/constants/cookies.ts
  src/hooks/useMe.ts
  src/lib/axiosInstance.ts
  src/middleware.ts
Labels: ✨Feature

#103 [style] layout css
  src/app/(with-header-sidebar)/layout.module.css
  src/app/(with-header-sidebar)/mydashboard/page.tsx
  src/app/(with-header-sidebar)/mypage/page.tsx
  src/app/layout.tsx
  src/components/MainContainer.module.css
  src/components/header/Header.tsx
  src/components/header/InvitationButton.module.css
  src/components/header/InvitationButton.tsx
  src/components/sidebar/SideBar.module.css
  src/components/sidebar/SideBar.tsx
  src/store/dashboardStore.ts
Labels: 🔨Refactor, 🎨HTML&CSS

#111 [feat] comment delete update
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Comments.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/CommentDetail.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/CommentDetail.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/Comments.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/Comments.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitations.tsx
  src/lib/commentService.ts
  src/types/comment.ts
Labels: ✨Feature

#110 [refactor] improve accesstoken handling
  src/app/(user-access)/login/page.tsx
  src/app/api/accessToken/route.ts
  src/app/api/login/route.ts
  src/hooks/useMe.ts
  src/lib/axiosInstance.ts
Labels: 🔨Refactor

#92 [feat] add signup api2
  src/api/auth/signup.ts
Labels: 📬API

#113 [style] improve card responsiveness
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/page.module.css
  src/components/MainContainer.module.css
  src/components/card/Tag.module.css
  src/components/sidebar/SideBar.module.css
Labels: 🎨HTML&CSS

#117 [feat] implement toast message
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateCardModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateCardModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/UpdateCardModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/UpdateCardModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/InvitationModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useInvitation.ts
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_hooks/useMember.ts
  src/app/(with-header-sidebar)/mypage/_components/Modal.module.css
  src/app/(with-header-sidebar)/mypage/_components/PasswordForm.tsx
  src/app/(with-header-sidebar)/mypage/_lib/userService.ts
  src/app/layout.tsx
  src/components/FileInput.tsx
  src/components/Toast.module.css
  src/components/Toast.tsx
  src/lib/boardService.ts
  src/lib/cardService.ts
  src/store/toastStore.ts
Labels: ✨Feature, 🎨HTML&CSS

#119 [feat] add modal for adding columns
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CloseButton.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/CloseButton.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/Column.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CommonColumnModal.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateColumnModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/SettingsColumnModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/Assignment.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useDashBoardView.ts
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/components/landing/Section/PrimarySection.module.css
  src/lib/boardService.ts
  src/lib/columnServie.ts
  src/store/cardStore.ts
  src/store/dashboardStore.ts
  src/types/dashboardView.ts
Labels: ✨Feature, 📬API

#122 [feat] dashboard restore
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/UpdateCardModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.module.css
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/comments/CommentDetail.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EditForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/invitations/MyInvitationCard.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/modal/Modal.module.css
  src/app/(with-header-sidebar)/mydashboard/_hooks/useDashboards.ts
  src/app/(with-header-sidebar)/mydashboard/_lib/myInvitationService.ts
  src/components/card/ColumnLabel.module.css
  src/components/header/DashboardMembers.module.css
  src/components/header/InvitationButton.module.css
  src/components/header/UserSection.module.css
  src/components/header/UserSection.tsx
  src/components/header/skeleton/UserInfoSkeleton.module.css
  src/components/sidebar/Dashboards.tsx
  src/hooks/useClickOutside.ts
  src/lib/boardService.ts
  src/lib/commentService.ts
  src/store/dashboardTriggerStore.ts
  src/store/toastStore.ts
Labels: 🔨Refactor

#124 [refactor] refetch card data once card is created, deleted, updated
  src/app/(with-header-sidebar)/dashboard/[id]/components/Card.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/CreateCardModal.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/CardInfo.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/components/card-detail/HeaderMenu.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/DeleteButton.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/edit/_components/EditForm.tsx
  src/app/(with-header-sidebar)/dashboard/[id]/hooks/useDashBoardView.ts
  src/app/(with-header-sidebar)/dashboard/[id]/page.tsx
  src/app/(with-header-sidebar)/mydashboard/_components/dashboards/CreateDashboardForm.tsx
  src/components/header/UserSection.tsx
  src/components/sidebar/Dashboards.tsx
  src/lib/cardService.ts
  src/middleware.ts
  src/store/dashboardStore.ts
  src/store/dashboardTriggerStore.ts
  src/store/triggerStore.ts
Labels: 🔨Refactor
